### ISSUE TITLE
Bad option: --listen

### ISSUE THREAD

**Issue by sandric** [NicolasPetton/jade#5] opened 2016-08-26 05:28 UTC
I installed `node-nightly`, but even after that I can not see any listen option. I tried `--inspect` and `--debug` but it runs the program straight away and when I try to connect from emacs to that port it gives me failure..

```
sandric@sandric-mac ~> node-nightly -v
v7.0.0-nightly2016082451f96dfcfc
sandric@sandric-mac ~> node -v
v5.1.0
sandric@sandric-mac ~> node-nightly --listen test.js
/usr/local/lib/node_modules/node-nightly/node-nightly/bin/node: bad option: --listen
```

**Comment by NicolasPetton** [comment] 2016-08-26 08:11
It is indeed --inspect, and I fixed the readme.

What happens when you use --inspect?

**Comment by sandric** [comment] 2016-08-26 13:50
If I run command in terminal I get:
```
sandric@sandric-mac ~> node-nightly --inspect test.js
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@62cd277117e6f8ec53e31b1be58290a6f7ab42ef/inspecto
r.html?experiments=true&v8only=true&ws=localhost:9229/node                                        
lal
0
1234
1
1234
2
1234
sandric@sandric-mac ~> 
```
Then in emacs with test.js buffer opened I run `jade-connect-to-nodejs` and get in message buffer:
```
websocket-open: make client process failed: Connection refused, :name, websocket to ws://127.0.0.1:9229/node, :buffer, nil, :host, 127.0.0.1, :service, 9229, :nowait, nil
```

Mb I didn't understand that you have to inspect waiting process in node - for example if code was an express application waiting for connection? Or if break point was set up? I saw there's stepping debugger in jade, should I use it for debug? Is there some doc mb how I can use it, I didn't find docs about it.

**Comment by NicolasPetton** [comment] 2016-08-26 16:06
sandric <notifications@github.com> writes:

> If I run command in terminal I get:
> ```
> sandric@sandric-mac ~> node-nightly --inspect test.js
> Debugger listening on port 9229.
> Warning: This is an experimental feature and could change at any time.
> To start debugging, open the following URL in Chrome:
>     chrome-devtools://devtools/remote/serve_file/@62cd277117e6f8ec53e31b1be58290a6f7ab42ef/inspecto
> r.html?experiments=true&v8only=true&ws=localhost:9229/node                                        
> lal
> 0
> 1234
> 1
> 1234
> 2
> 1234
> sandric@sandric-mac ~> 
> ```
> Then in emacs with test.js buffer opened I run `jade-connect-to-nodejs` and get in message buffer:
> ```
> websocket-open: make client process failed: Connection refused, :name,
> websocket to ws://127.0.0.1:9229/node, :buffer, nil, :host, 127.0.0.1,
> :service, 9229, :nowait, nil

Has your node process terminated by the time you try to connect to it
using Jade?

As long as you make sure that your nodejs process is alive when
connecting jade to it, you should not have to do anything else.

If your process is indeed alive when trying to connect, can you send me
a minimal test.js file that shows the issue?

**Comment by sandric** [comment] 2016-08-27 01:01
No, my project was simple test file that just runs couple of commands for testing output. I understand now - I should read docs more carefully - there's "eliminate debug lexems" in missing list, if you'll run command as so `node-nightly --inspect --debug-brk <your-file.js>` node will place break point at first line just like gdb would do and you can step from there, so you can then do `jade-connect-to-nodejs` and see proper js debugger buffer. 
The problem in there though in that it is also creates js repl buffer and if you try to evaluate smth from there you will get an error:
```
Cannot find default execution context
Error during redisplay: (jit-lock-function 352) signaled (wrong-type-argument stringp nil)
```
You can reproduce that easily - simply create test file with console.log smth, then type in terminal `node-nightly --inspect --debug-brk <your-file.js>` and M-x in emacs `jade-connect-to-nodejs`. Then open buffer *JS REPL ...* and try to type smth there.

**Comment by NicolasPetton** [comment] 2016-08-27 09:49
sandric <notifications@github.com> writes:

> You can reproduce that easily - simply create test file with
> console.log smth, then type in terminal `node-nightly --inspect
> --debug-brk <your-file.js>` and M-x in emacs
> `jade-connect-to-nodejs`. Then open buffer *JS REPL ...* and try to
> type smth there.

Something else must be wrong, as I can evaluate JS code in the REPL
following your recipe without any jit-lock error.

What version of Emacs are you using?

**Comment by sandric** [comment] 2016-08-27 17:01
Hm, my emacs is 25.1.50.1. Maybe it corresponds to other error I get if I connect to chrome - after connect from emacs it looks like everything works normal, but as soon as I open developer tools console in chrome I get failure in emacs jade repl buffer with other jit-lock-function error:

`Error during redisplay: (jit-lock-function 2502) signaled (wrong-type-argument stringp nil)`

Don't you get the same error?

**Comment by sandric** [comment] 2016-08-27 19:12
Ok, I figured out that its not the issue with font-lock, although the error is spawned - if I turn off font-lock in emacs the real error is spawned when I try to connect to nodejs process.
When I try to connect to default repl, started with `node-nightly --inspect` in repl buffer when trying to type smth I get `Cannot find default execution context`. The same with `node-nightly --inspect --debug-brk test.js`.

As of connecting to chrome - when I try to open developer tools the real errors are those, don't know the issue though, total mistery for me:
```
Socket connection closed
Entering debugger...
WS Error! on-close (wrong-type-argument stringp nil)
websocket-outer-filter: Error response received from websocket server
```

**Comment by NicolasPetton** [comment] 2016-08-28 07:47
I think there are different things here:

- When you open the devtools in Chrome, it will close the connection to
  Jade, that is just how Chrome works and it is expected
  
- When a connection to Chrome is closed, you should not get an
  exception, so that seems to be a bug
  
- For some reason, you get a `Cannot find default execution context` in
  node-nightly, which is another bug, that I cannot reproduce

Could you open another issue for Chrome, explaining how to reproduce it 
(I could not with the info I have)?

Could you also post the version of node-nightly you are using?

**Comment by sandric** [comment] 2016-08-30 01:01
@NicolasPetton Ok, I'll try to create separate issue for chrome, thats right.
As for my `node-nightly`, npm package version is `1.6.0` and `node-nightly --version` for corresponding node version is giving me `v7.0.0-nightly2016082451f96dfcfc`

**Comment by NicolasPetton** [comment] 2016-09-10 22:07
I have v7.0.0-nightly20160727868638b903 here, and Jade works fine, I can try upgrading it.

Regarding the issue when the connection to Chrome is closed, could you create an issue?

**Comment by NicolasPetton** [comment] 2017-04-06 09:52
@sandric Both the Chrome and NodeJS backend have changed quite a lot, so I'm closing this issue.

Feel free to reopen it if it's still an issue for you.

**Closed by NicolasPetton** 2017-04-06 09:52 UTC
