### ISSUE TITLE
WS Error when trying to connect to nodejs process

### ISSUE THREAD

**Issue by CSRaghunandan** [NicolasPetton/jade#15] opened 2016-12-13 14:58 UTC
I get the following error when I try to connect to a nodejs process

```
WS Error! on-close (wrong-type-argument stringp nil)
error in process filter: websocket-outer-filter: Invalid HTTP header sent
error in process filter: Invalid HTTP header sent
```

This is what I got in `*backtrace*` when I enabled `toggle-debug-on-error`

```
Debugger entered--Lisp error: (websocket-invalid-header . "Invalid HTTP status line")
  signal(websocket-invalid-header "Invalid HTTP status line")
  websocket-outer-filter([cl-struct-websocket closed nil #[257 "\301\203\301 \210\302\300\"\207" ["ws://127.0.0.1:9229/node" nil jade-webkit--handle-ws-open] 4 "\n\n(fn WS)"] jade-webkit--handle-ws-message jade-webkit--handle-ws-closed jade-webkit--handle-ws-error nil nil nil "ws://127.0.0.1:9229/node" nil nil #<process websocket to ws://127.0.0.1:9229/node> nil "yfSHlJgu85t/P7Pku3qBnVAV5X4=" nil] "HTTP/1.0 400 Bad Request
\nContent-Type: text/html; charset=UTF-8
\n
\nWebSockets request was expected
\n")
  #[(process output) "\303\304\"\305	\n\")\207" [process websocket output process-get :websocket websocket-outer-filter] 3](#<process websocket to ws://127.0.0.1:9229/node> "HTTP/1.0 400 Bad Request
\nContent-Type: text/html; charset=UTF-8
\n
\nWebSockets request was expected
\n")

```

I'm running emacs master build on macOS Sierra.

**Comment by NicolasPetton** [comment] 2016-12-13 16:14
Hi!

What version of Chrom{e|ium} are you using?

**Comment by CSRaghunandan** [comment] 2016-12-13 16:33
Chrome version: `Version 54.0.2840.98 (64-bit)`

**Comment by NicolasPetton** [comment] 2016-12-13 17:00
No, but it looks like  you're trying to connect to a nodejs process.
How did you try to connect to chrome?

Can you try starting chrome like this:

`chrome --remote-debugging-port=9222`

On macOS, it should be something like:

`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`

Then from Emacs `M-x jade-connect-to-chrome`

**Comment by CSRaghunandan** [comment] 2016-12-13 17:20
That indeed works. I've an alias for the same. I can connect to a chrome tab no problem. 
But, I'm unable to connect to a nodejs process

**Comment by NicolasPetton** [comment] 2016-12-13 19:42
What version of nodejs are you running?

**Comment by CSRaghunandan** [comment] 2016-12-14 04:16
`nodejs v.7.2.1`
Umm is it because I'm emacs master build that the connection to nodejs process is refusing?

**Comment by NicolasPetton** [comment] 2016-12-14 09:15
@CSRaghunandan no, it shouldn't be, I'll check what's wrong!

**Comment by NicolasPetton** [comment] 2016-12-14 21:08
I found what's wrong: nodejs 7.x.x uses a different version of the remote debugger protocol.
I'll push a fix soon, thanks for reporting the issue!

**Comment by CSRaghunandan** [comment] 2016-12-15 03:29
Thank for taking a look into this 👍

**Comment by ldk-lx** [comment] 2017-02-13 23:35
I am experiencing this issue with node 6.9.1, 6.9.5, and 7.5.0. So I am not sure it is version-related. The error I get with 6.9.5 is as follows:

```
Debugger entered--Lisp error: (websocket-invalid-header . "Invalid HTTP status line")
  signal(websocket-invalid-header "Invalid HTTP status line")
  websocket-outer-filter([cl-struct-websocket closed nil (closure ((on-open) (websocket-url . "ws://127.0.0.1:9229/node") (url . "ws://127.0.0.1:9229/node") t) (ws) (if on-open (progn (funcall on-open))) (jade-webkit--handle-ws-open ws url)) jade-webkit--handle-ws-message jade-webkit--handle-ws-closed jade-webkit--handle-ws-error nil nil nil "ws://127.0.0.1:9229/node" nil nil #<process websocket to ws://127.0.0.1:9229/node> nil "zPlBbGHjkz4B4QORFIAc/OlCwdU=" nil] "HTTP/1.0 400 Bad Request
\nContent-Type: text/html; charset=UTF-8
\n
\nWebSockets request was expected
\n")
  #[(process output) "\303\304\"\305	\n\")\207" [process websocket output process-get :websocket websocket-outer-filter] 3](#<process websocket to ws://127.0.0.1:9229/node> "HTTP/1.0 400 Bad Request
\nContent-Type: text/html; charset=UTF-8
\n
\nWebSockets request was expected
\n")
  read-event(nil t 2)
  sit-for(2)
  execute-extended-command(nil "jade-connect-to-nodejs" "jade-connect-to-no")
  funcall-interactively(execute-extended-command nil "jade-connect-to-nodejs" "jade-connect-to-no")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by NicolasPetton** [comment] 2017-02-14 10:16
ldk-lx <notifications@github.com> writes:

> I am experiencing this issue with node 6.9.1, 6.9.5, and 7.5.0. So I
> am not sure it is version-related. The error I get with 6.9.5 is as
> follows:

It is actually a problem with updating to the remote debugger protocol
of the latest version of Chrome, which has diverged from the one used in
Node.  I have a work in progress branch with a fix, I'll push an update
soon.

**Comment by NicolasPetton** [comment] 2017-02-24 17:00
The issue should be fixed with commit cc68a200608e91176f03f0ef59c334e590ad72ea!

**Closed by NicolasPetton** 2017-02-24 17:00 UTC

**Comment by s-kostyaev** [comment] 2017-02-28 08:44
I have the same error with chromium Version 56.0.2924.87 (64-bit):
```
Contacting host: 127.0.0.1:9222
WS Error! on-open (wrong-type-argument stringp nil)
WS Error! on-message (wrong-type-argument integer-or-marker-p nil)
```

**Comment by NicolasPetton** [comment] 2017-02-28 13:22
@s-kostyaev can you give me the version of jade you're using, as well as Emacs? 

Also, is Chrome running with the `--remote-debugging-port` flag set?

**Comment by s-kostyaev** [comment] 2017-03-01 03:18
@NicolasPetton jade  20170224.922, emacs 25.1, chromium has running with `--remote-debugging-port` flag.

**Comment by NicolasPetton** [comment] 2017-03-01 12:49
@s-kostyaev I cannot reproduce the issue, but I'll investigate more. 

What OS are you using?
Can you open another issue as this one was related to nodejs?

**Comment by s-kostyaev** [comment] 2017-03-01 12:56
I use GNU/Linux. I will open another issue a little bit later.

**Comment by NicolasPetton** [comment] 2017-03-01 13:03
@s-kostyaev I need a bit of help to understand what's going on 😄 

- When you try to connect to a tab, do you get the list of Chromium tabs in the minibuffer? 
- Can you access http://127.0.0.1:9222/ from Chrome?

**Comment by s-kostyaev** [comment] 2017-03-02 05:18
Sorry for wasting your time. I'll try again and all works fine.

**Comment by NicolasPetton** [comment] 2017-03-02 09:06
@s-kostyaev I'm glad it works for you now!
